<%@ page language="java" isELIgnored="false" contentType="text/html; charset=utf8" pageEncoding="utf8"%>
<div id="footer">
	<span class="footer">Generated by <a href="">YangShengTang</a> | Copyright &copy; 2014 All Rights Reserved</span> 
</div><!-- end footer --> 

